Repository ongakken/terminalInsanityCLI, pull requests merged in 2021-05, with the labels that each got.

#35 Create config.yml
  .github/config.yml
Labels: kind/ci, size/tiny

#36 update from master;
  .github/config.yml
  .github/stale.yml
Labels: kind/feature, size/small

#46 Declaration check
  terminalInsanityCONSOLE/main.h
Labels: enhancement, kind/build, size/medium
